2019-05-28 16:45:38,785 start_driver.py[line:26] INFO: start app...
2019-05-28 16:56:25,598 start_driver.py[line:26] INFO: start app...
2019-05-28 17:57:04,733 start_driver.py[line:26] INFO: start app...
2019-05-28 17:57:42,403 common_func.py[line:53] ERROR: No element found
2019-05-29 11:13:20,719 start_driver.py[line:26] INFO: start app...
2019-05-29 11:14:06,841 common_func.py[line:53] ERROR: No element found
2019-05-29 11:15:03,718 start_driver.py[line:26] INFO: start app...
2019-05-29 11:15:51,180 common_func.py[line:53] ERROR: No element found
2019-05-29 11:17:22,106 start_driver.py[line:26] INFO: start app...
2019-05-29 11:19:35,958 start_driver.py[line:26] INFO: start app...
2019-05-29 11:26:32,478 start_driver.py[line:26] INFO: start app...
2019-05-29 12:40:51,976 start_driver.py[line:26] INFO: start app...
2019-05-29 13:43:15,598 start_driver.py[line:26] INFO: start app...
2019-05-29 13:45:11,652 start_driver.py[line:26] INFO: start app...
2019-05-29 13:47:39,988 start_driver.py[line:26] INFO: start app...
2019-05-29 13:49:13,230 start_driver.py[line:26] INFO: start app...
2019-05-29 14:12:31,184 start_driver.py[line:26] INFO: start app...
2019-05-29 14:49:36,405 start_driver.py[line:26] INFO: start app...
2019-05-29 14:51:00,808 common_func.py[line:47] INFO: get login screenshot
2019-05-29 14:51:04,123 loginPage.py[line:44] INFO: login success!
2019-05-29 14:51:29,540 loginPage.py[line:58] INFO: logout success!
2019-05-29 14:51:29,540 common_func.py[line:47] INFO: get logout screenshot
2019-05-29 15:55:51,200 start_driver.py[line:26] INFO: start app...
2019-05-29 15:57:28,422 common_func.py[line:47] INFO: get login screenshot
2019-05-29 15:57:31,452 loginPage.py[line:56] INFO: login success!
2019-05-29 15:57:58,721 loginPage.py[line:70] INFO: logout success!
2019-05-29 15:57:58,721 common_func.py[line:47] INFO: get logout screenshot
2019-05-29 17:07:15,843 read_csv.py[line:19] ERROR: [Errno 2] No such file or directory: 'E:\\PythonAppium\\AppiumProject\\data\\account1.csv'
2019-05-29 17:07:53,769 read_csv.py[line:19] ERROR: list index out of range
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:18:12,419 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:12,420 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:12,420 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:21,825 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:21,825 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:55:11,715 getConfig.py[line:19] ERROR: No option 'host1' in section: 'email'
2019-05-29 17:55:33,510 getConfig.py[line:19] ERROR: No section: 'email1'
2019-05-30 11:19:58,670 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 11:19:58,680 start_driver.py[line:26] INFO: start app...
2019-05-30 11:20:40,564 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 11:20:45,569 start_driver.py[line:26] INFO: start app...
2019-05-30 11:24:04,642 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 11:24:04,646 start_driver.py[line:26] INFO: start app...
2019-05-30 11:24:49,246 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 11:24:54,252 start_driver.py[line:26] INFO: start app...
2019-05-30 11:32:46,182 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 11:32:46,186 start_driver.py[line:26] INFO: start app...
2019-05-30 11:33:17,780 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 11:33:22,787 start_driver.py[line:26] INFO: start app...
2019-05-30 11:35:07,408 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 11:35:07,412 start_driver.py[line:26] INFO: start app...
2019-05-30 11:35:47,731 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 11:35:52,733 start_driver.py[line:26] INFO: start app...
2019-05-30 11:37:33,237 start_driver.py[line:26] INFO: start app...
2019-05-30 11:38:39,170 start_driver.py[line:26] INFO: start app...
2019-05-30 11:41:13,699 start_driver.py[line:26] INFO: start app...
2019-05-30 11:42:46,537 common_func.py[line:47] INFO: get login screenshot
2019-05-30 11:42:49,241 loginPage.py[line:56] INFO: login success!
2019-05-30 12:27:55,370 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 12:27:55,373 start_driver.py[line:26] INFO: start app...
2019-05-30 12:28:22,715 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 12:28:27,718 start_driver.py[line:26] INFO: start app...
2019-05-30 12:58:09,297 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 12:58:09,300 start_driver.py[line:26] INFO: start app...
2019-05-30 12:58:57,146 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 13:00:03,135 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 13:00:03,137 start_driver.py[line:26] INFO: start app...
2019-05-30 13:00:53,685 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 13:02:44,049 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 13:02:44,052 start_driver.py[line:26] INFO: start app...
2019-05-30 13:04:03,747 common_func.py[line:47] INFO: get login screenshot
2019-05-30 13:04:06,191 loginPage.py[line:56] INFO: login success!
2019-05-30 13:04:08,828 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 13:50:21,969 run_test.py[line:15] INFO: start run test case！
2019-05-30 13:50:21,969 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 13:50:21,974 start_driver.py[line:26] INFO: start app...
2019-05-30 13:51:02,243 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 13:51:18,903 run_test.py[line:15] INFO: start run test case！
2019-05-30 13:51:18,903 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 13:51:18,911 start_driver.py[line:26] INFO: start app...
2019-05-30 13:52:04,628 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 14:08:36,627 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:08:36,628 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 14:08:36,631 start_driver.py[line:26] INFO: start app...
2019-05-30 14:13:04,279 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:13:04,279 unittestFunc.py[line:9] INFO: =====setUp=====
2019-05-30 14:13:04,281 start_driver.py[line:26] INFO: start app...
2019-05-30 14:13:34,529 start_driver.py[line:31] ERROR: fail to connect devices!
2019-05-30 14:13:34,531 unittestFunc.py[line:14] INFO: =====tearDown=====
2019-05-30 14:14:18,598 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:14:18,601 start_driver.py[line:26] INFO: start app...
2019-05-30 14:14:48,882 start_driver.py[line:31] ERROR: fail to connect devices!
2019-05-30 14:17:22,645 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:17:22,648 start_driver.py[line:26] INFO: start app...
2019-05-30 14:21:27,810 run_test.py[line:15] INFO: start run test case！
2019-05-30 14:21:27,812 start_driver.py[line:26] INFO: start app...
2019-05-30 15:11:13,317 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:11:13,320 start_driver.py[line:26] INFO: start app...
2019-05-30 15:17:40,423 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:17:40,429 start_driver.py[line:26] INFO: start app...
2019-05-30 15:18:36,250 common_func.py[line:40] ERROR: 引导页滑动失败!
2019-05-30 15:24:43,367 start_driver.py[line:26] INFO: start app...
2019-05-30 15:41:10,101 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:41:10,105 start_driver.py[line:26] INFO: start app...
2019-05-30 15:41:47,975 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 15:42:10,175 start_driver.py[line:26] INFO: start app...
2019-05-30 15:44:08,561 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:44:08,563 start_driver.py[line:26] INFO: start app...
2019-05-30 15:46:05,751 start_driver.py[line:26] INFO: start app...
2019-05-30 15:55:59,542 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:55:59,544 start_driver.py[line:26] INFO: start app...
2019-05-30 15:56:04,609 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 15:56:04,610 common_func.py[line:20] ERROR: Failed to get screen size
2019-05-30 15:56:04,610 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 15:58:44,605 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:58:44,607 start_driver.py[line:26] INFO: start app...
2019-05-30 15:59:14,423 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 15:59:57,305 run_test.py[line:15] INFO: start run test case！
2019-05-30 15:59:57,310 start_driver.py[line:26] INFO: start app...
2019-05-30 16:00:49,628 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 16:01:59,279 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:01:59,285 start_driver.py[line:26] INFO: start app...
2019-05-30 16:03:50,707 start_driver.py[line:26] INFO: start app...
2019-05-30 16:13:24,308 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:13:24,311 start_driver.py[line:26] INFO: start app...
2019-05-30 16:13:55,486 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:15:53,863 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:15:53,867 start_driver.py[line:26] INFO: start app...
2019-05-30 16:23:14,235 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:23:14,238 start_driver.py[line:26] INFO: start app...
2019-05-30 16:23:42,673 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:24:41,537 start_driver.py[line:26] INFO: start app...
2019-05-30 16:25:34,613 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:26:30,499 start_driver.py[line:26] INFO: start app...
2019-05-30 16:27:19,536 common_func.py[line:44] ERROR: 引导页滑动失败!
2019-05-30 16:27:19,537 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:28:09,572 start_driver.py[line:26] INFO: start app...
2019-05-30 16:29:01,012 common_func.py[line:44] ERROR: 引导页滑动失败!
2019-05-30 16:29:01,012 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:29:53,921 start_driver.py[line:26] INFO: start app...
2019-05-30 16:30:34,589 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:30:39,154 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:31:01,870 start_driver.py[line:26] INFO: start app...
2019-05-30 16:31:45,674 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:31:54,999 common_func.py[line:62] ERROR: 启动失败!
2019-05-30 16:33:18,631 start_driver.py[line:26] INFO: start app...
2019-05-30 16:33:23,651 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:33:23,651 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:33:48,588 start_driver.py[line:26] INFO: start app...
2019-05-30 16:33:53,611 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:33:53,611 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:34:57,776 start_driver.py[line:26] INFO: start app...
2019-05-30 16:35:02,795 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:35:02,795 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:37:20,488 start_driver.py[line:26] INFO: start app...
2019-05-30 16:37:20,506 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:37:20,506 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:37:29,449 start_driver.py[line:26] INFO: start app...
2019-05-30 16:37:29,462 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:37:29,462 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:37:40,362 start_driver.py[line:26] INFO: start app...
2019-05-30 16:37:40,376 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:37:40,376 common_func.py[line:21] ERROR: Failed to get screen size
2019-05-30 16:37:40,376 common_func.py[line:44] ERROR: 引导页滑动失败!
2019-05-30 16:37:40,376 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:38:09,481 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:38:09,484 start_driver.py[line:26] INFO: start app...
2019-05-30 16:38:09,497 start_driver.py[line:32] ERROR: fail to connect devices!
2019-05-30 16:38:09,498 common_func.py[line:21] ERROR: Failed to get screen size
2019-05-30 16:38:09,499 common_func.py[line:44] ERROR: 引导页滑动失败!
2019-05-30 16:38:56,573 start_driver.py[line:26] INFO: start app...
2019-05-30 16:39:23,567 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:40:11,410 start_driver.py[line:26] INFO: start app...
2019-05-30 16:40:53,004 common_func.py[line:54] INFO: get startapp screenshot
2019-05-30 16:40:58,935 common_func.py[line:63] ERROR: 启动失败!
2019-05-30 16:41:25,655 start_driver.py[line:26] INFO: start app...
2019-05-30 16:42:09,372 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:42:55,159 start_driver.py[line:26] INFO: start app...
2019-05-30 16:43:33,747 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:44:20,315 start_driver.py[line:26] INFO: start app...
2019-05-30 16:45:01,617 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:45:29,262 start_driver.py[line:26] INFO: start app...
2019-05-30 16:46:23,071 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:46:30,217 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 16:46:55,902 start_driver.py[line:26] INFO: start app...
2019-05-30 16:47:52,685 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:49:08,302 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:49:08,305 start_driver.py[line:26] INFO: start app...
2019-05-30 16:49:43,400 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 16:50:18,155 start_driver.py[line:26] INFO: start app...
2019-05-30 16:52:06,301 start_driver.py[line:26] INFO: start app...
2019-05-30 16:52:47,653 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 16:53:30,645 start_driver.py[line:26] INFO: start app...
2019-05-30 16:54:14,283 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 16:54:51,245 run_test.py[line:15] INFO: start run test case！
2019-05-30 16:54:51,247 start_driver.py[line:26] INFO: start app...
2019-05-30 16:56:40,524 common_func.py[line:53] INFO: get login screenshot
2019-05-30 16:56:43,344 loginPage.py[line:56] INFO: login success!
2019-05-30 17:00:37,985 run_test.py[line:15] INFO: start run test case！
2019-05-30 17:00:37,989 start_driver.py[line:26] INFO: start app...
2019-05-30 17:01:37,624 start_driver.py[line:26] INFO: start app...
2019-05-30 17:02:19,350 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:02:39,796 start_driver.py[line:26] INFO: start app...
2019-05-30 17:03:49,224 start_driver.py[line:26] INFO: start app...
2019-05-30 17:04:45,984 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:44:48,837 run_test.py[line:15] INFO: start run test case！
2019-05-30 17:44:48,840 start_driver.py[line:26] INFO: start app...
2019-05-30 17:45:19,863 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:45:46,152 start_driver.py[line:26] INFO: start app...
2019-05-30 17:46:16,878 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:46:42,641 start_driver.py[line:26] INFO: start app...
2019-05-30 17:47:16,110 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 17:47:42,253 start_driver.py[line:26] INFO: start app...
2019-05-30 17:48:13,429 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 21:14:07,756 run_test.py[line:15] INFO: start run test case！
2019-05-30 21:14:20,589 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:17:10,020 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:20:57,747 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:20:57,747 common_func.py[line:53] INFO: get startapp screenshot
2019-05-30 21:21:22,022 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:21:22,022 common_func.py[line:20] ERROR: Failed to get screen size
2019-05-30 21:21:22,022 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-30 21:21:32,319 start_driver.py[line:33] ERROR: fail to connect devices!
2019-05-30 21:22:24,908 start_driver.py[line:33] ERROR: 'uiautomator2'
2019-05-30 21:26:18,509 start_driver.py[line:27] INFO: start app...
2019-05-30 21:28:00,280 run_test.py[line:15] INFO: start run test case！
2019-05-30 21:28:00,285 start_driver.py[line:27] INFO: start app...
2019-05-30 21:29:04,648 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:29:04,940 loginPage.py[line:56] INFO: login success!
2019-05-30 21:29:11,873 start_driver.py[line:27] INFO: start app...
2019-05-30 21:30:16,092 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:30:16,377 loginPage.py[line:56] INFO: login success!
2019-05-30 21:30:24,998 start_driver.py[line:27] INFO: start app...
2019-05-30 21:31:28,758 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:31:29,041 loginPage.py[line:56] INFO: login success!
2019-05-30 21:31:35,508 start_driver.py[line:27] INFO: start app...
2019-05-30 21:32:40,281 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:32:40,556 loginPage.py[line:56] INFO: login success!
2019-05-30 21:40:19,114 run_test.py[line:15] INFO: start run test case！
2019-05-30 21:40:19,118 start_driver.py[line:27] INFO: start app...
2019-05-30 21:41:24,706 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:41:25,638 loginPage.py[line:77] INFO: login success
2019-05-30 21:41:32,135 start_driver.py[line:27] INFO: start app...
2019-05-30 21:42:36,544 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:42:39,119 loginPage.py[line:77] INFO: login success
2019-05-30 21:42:45,858 start_driver.py[line:27] INFO: start app...
2019-05-30 21:43:50,556 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:43:51,079 loginPage.py[line:77] INFO: login success
2019-05-30 21:43:57,357 start_driver.py[line:27] INFO: start app...
2019-05-30 21:45:01,084 common_func.py[line:53] INFO: get login screenshot
2019-05-30 21:45:03,672 loginPage.py[line:77] INFO: login success
2019-05-30 22:26:44,086 run_test.py[line:15] INFO: start run test case！
2019-05-30 22:26:44,091 start_driver.py[line:27] INFO: start app...
2019-05-30 22:27:48,440 common_func.py[line:53] INFO: get login screenshot
2019-05-30 22:27:49,201 loginPage.py[line:82] INFO: login success
2019-05-30 22:27:55,497 start_driver.py[line:27] INFO: start app...
2019-05-30 22:28:58,912 common_func.py[line:53] INFO: get login screenshot
2019-05-30 22:29:01,468 loginPage.py[line:82] INFO: login success
2019-05-30 22:29:07,794 start_driver.py[line:27] INFO: start app...
2019-05-30 22:30:12,075 common_func.py[line:53] INFO: get login screenshot
2019-05-30 22:30:12,606 loginPage.py[line:82] INFO: login success
2019-05-30 22:30:18,979 start_driver.py[line:27] INFO: start app...
2019-05-30 22:31:22,428 common_func.py[line:53] INFO: get login screenshot
2019-05-30 22:31:24,991 loginPage.py[line:82] INFO: login success
2019-05-30 23:17:36,246 run_test.py[line:15] INFO: start run test case！
2019-05-30 23:17:36,251 start_driver.py[line:27] INFO: start app...
2019-05-30 23:18:40,838 common_func.py[line:53] INFO: get login screenshot
2019-05-30 23:18:55,169 loginPage.py[line:83] INFO: login success!
2019-05-30 23:19:01,470 start_driver.py[line:27] INFO: start app...
2019-05-30 23:20:05,210 common_func.py[line:53] INFO: get login screenshot
2019-05-30 23:20:20,937 loginPage.py[line:79] INFO: login fail!
2019-05-30 23:20:20,937 common_func.py[line:53] INFO: get login fail screenshot
2019-05-30 23:20:27,400 start_driver.py[line:27] INFO: start app...
2019-05-30 23:21:31,366 common_func.py[line:53] INFO: get login screenshot
2019-05-30 23:21:47,096 loginPage.py[line:79] INFO: login fail!
2019-05-30 23:21:47,096 common_func.py[line:53] INFO: get login fail screenshot
2019-05-30 23:21:53,580 start_driver.py[line:27] INFO: start app...
2019-05-30 23:22:57,584 common_func.py[line:53] INFO: get login screenshot
2019-05-30 23:23:12,926 loginPage.py[line:79] INFO: login fail!
2019-05-30 23:23:12,926 common_func.py[line:53] INFO: get login fail screenshot
2019-05-31 10:23:00,817 run_test.py[line:15] INFO: start run test case！
2019-05-31 10:23:00,835 start_driver.py[line:27] INFO: start app...
2019-05-31 10:24:30,845 common_func.py[line:53] INFO: get login screenshot
2019-05-31 10:25:13,090 loginPage.py[line:83] INFO: login success!
2019-05-31 10:25:19,866 start_driver.py[line:27] INFO: start app...
2019-05-31 10:26:28,981 common_func.py[line:53] INFO: get login screenshot
2019-05-31 10:26:44,988 loginPage.py[line:79] INFO: login fail!
2019-05-31 10:26:44,988 common_func.py[line:53] INFO: get login fail screenshot
2019-05-31 10:26:52,073 start_driver.py[line:27] INFO: start app...
2019-05-31 10:28:01,388 common_func.py[line:53] INFO: get login screenshot
2019-05-31 10:28:17,426 loginPage.py[line:79] INFO: login fail!
2019-05-31 10:28:17,426 common_func.py[line:53] INFO: get login fail screenshot
2019-05-31 10:28:24,569 start_driver.py[line:27] INFO: start app...
2019-05-31 12:40:10,172 run_test.py[line:15] INFO: start run test case！
2019-05-31 12:40:10,176 start_driver.py[line:27] INFO: start app...
2019-05-31 12:41:09,262 start_driver.py[line:27] INFO: start app...
2019-05-31 12:42:13,834 start_driver.py[line:27] INFO: start app...
2019-05-31 12:43:25,749 run_test.py[line:15] INFO: start run test case！
2019-05-31 12:43:25,752 start_driver.py[line:27] INFO: start app...
2019-05-31 12:44:18,647 start_driver.py[line:33] ERROR: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

2019-05-31 12:44:18,649 common_func.py[line:20] ERROR: Failed to get screen size
2019-05-31 12:44:18,649 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-05-31 12:44:23,681 start_driver.py[line:27] INFO: start app...
2019-05-31 17:10:24,016 sendEmail.py[line:36] ERROR: {'ss': (550, b'Invalid User: ss')}
2019-05-31 17:10:49,512 sendEmail.py[line:36] ERROR: {'ss': (550, b'Invalid User: ss')}
2019-05-31 17:11:22,603 sendEmail.py[line:36] ERROR: (554, b'DT:SPM 163 smtp12,EMCowADnoRSa7_BcY7HdIQ--.39993S2 1559293850,please see http://mail.163.com/help/help_spam_16.htm?ip=117.139.166.12&hostid=smtp12&time=1559293850')
2019-05-31 17:11:54,447 sendEmail.py[line:36] ERROR: (554, b'DT:SPM 163 smtp12,EMCowACXRju67_BcC8_dIQ--.41833S2 1559293882,please see http://mail.163.com/help/help_spam_16.htm?ip=117.139.166.12&hostid=smtp12&time=1559293882')
2019-05-31 17:13:54,998 sendEmail.py[line:36] ERROR: (554, b'DT:SPM 163 smtp12,EMCowAAH3Cky8PBctgDeIQ--.41398S2 1559294003,please see http://mail.163.com/help/help_spam_16.htm?ip=117.139.166.12&hostid=smtp12&time=1559294003')
2019-06-01 16:07:37,706 sendEmail.py[line:41] ERROR: 'list' object has no attribute 'encode'
2019-06-01 16:54:56,422 sendEmail.py[line:41] ERROR: (554, b'DT:SPM 163 smtp13,EcCowAAXi_k8PfJctIXFIw--.64110S2 1559379261,please see http://mail.163.com/help/help_spam_16.htm?ip=117.139.208.11&hostid=smtp13&time=1559379261')
2019-06-01 16:55:12,415 sendEmail.py[line:41] ERROR: (554, b'DT:SPM 163 smtp13,EcCowAD3TFpLPfJcWo3FIw--.51S2 1559379277,please see http://mail.163.com/help/help_spam_16.htm?ip=117.139.208.11&hostid=smtp13&time=1559379277')
2019-06-01 17:14:24,625 run_test.py[line:16] INFO: start run test case！
2019-06-01 17:14:24,630 start_driver.py[line:27] INFO: start app...
2019-06-01 17:15:23,166 start_driver.py[line:27] INFO: start app...
2019-06-01 17:16:11,096 start_driver.py[line:27] INFO: start app...
2019-06-01 17:18:51,440 run_test.py[line:16] INFO: start run test case！
2019-06-01 17:18:51,445 start_driver.py[line:27] INFO: start app...
2019-06-01 17:19:37,906 start_driver.py[line:27] INFO: start app...
2019-06-01 17:20:25,528 start_driver.py[line:27] INFO: start app...
2019-06-01 17:23:31,521 run_test.py[line:16] INFO: start run test case！
2019-06-01 17:23:31,525 start_driver.py[line:27] INFO: start app...
2019-06-01 17:23:36,556 start_driver.py[line:33] ERROR: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003574DA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2019-06-01 17:23:36,557 common_func.py[line:20] ERROR: Failed to get screen size
2019-06-01 17:23:36,558 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-06-01 17:23:45,826 run_test.py[line:16] INFO: start run test case！
2019-06-01 17:23:45,830 start_driver.py[line:27] INFO: start app...
2019-06-01 17:24:32,997 start_driver.py[line:27] INFO: start app...
2019-06-01 17:25:18,352 start_driver.py[line:27] INFO: start app...
2019-06-01 17:26:31,558 start_driver.py[line:27] INFO: start app...
2019-06-01 17:27:36,202 common_func.py[line:53] INFO: get login screenshot
2019-06-01 17:32:21,770 run_test.py[line:16] INFO: start run test case！
2019-06-01 17:32:21,775 start_driver.py[line:27] INFO: start app...
2019-06-01 17:33:26,688 common_func.py[line:53] INFO: get login screenshot
2019-06-01 17:33:39,996 loginPage.py[line:83] INFO: login success!
2019-06-01 17:33:45,039 start_driver.py[line:27] INFO: start app...
2019-06-01 17:34:49,766 common_func.py[line:53] INFO: get login screenshot
2019-06-01 17:35:05,410 loginPage.py[line:79] INFO: login fail!
2019-06-01 17:35:05,410 common_func.py[line:53] INFO: get login fail screenshot
2019-06-01 17:35:10,653 start_driver.py[line:27] INFO: start app...
2019-06-01 17:36:15,553 common_func.py[line:53] INFO: get login screenshot
2019-06-01 17:36:31,307 loginPage.py[line:79] INFO: login fail!
2019-06-01 17:36:31,307 common_func.py[line:53] INFO: get login fail screenshot
2019-06-01 17:36:36,547 start_driver.py[line:27] INFO: start app...
2019-06-01 17:37:42,041 common_func.py[line:53] INFO: get login screenshot
2019-06-01 17:37:57,802 loginPage.py[line:79] INFO: login fail!
2019-06-01 17:37:57,802 common_func.py[line:53] INFO: get login fail screenshot
2019-06-01 17:42:31,788 start_driver.py[line:27] INFO: start app...
2019-06-01 17:43:04,869 common_func.py[line:53] INFO: get startapp screenshot
2019-06-01 17:44:50,481 run_test.py[line:16] INFO: start run test case！
2019-06-01 17:44:50,487 start_driver.py[line:27] INFO: start app...
2019-06-01 17:45:54,826 common_func.py[line:53] INFO: get login screenshot
2019-06-01 17:46:09,264 loginPage.py[line:83] INFO: login success!
2019-06-01 17:57:28,785 run_test.py[line:16] INFO: start run test case！
2019-06-01 17:57:28,790 start_driver.py[line:27] INFO: start app...
2019-06-01 17:58:33,056 common_func.py[line:53] INFO: get login screenshot
2019-06-01 17:58:46,755 loginPage.py[line:83] INFO: login success!
2019-06-01 18:01:40,420 run_test.py[line:16] INFO: start run test case！
2019-06-01 18:01:40,424 start_driver.py[line:27] INFO: start app...
2019-06-01 18:02:44,275 common_func.py[line:53] INFO: get login screenshot
2019-06-01 18:02:59,265 loginPage.py[line:83] INFO: login success!
2019-06-01 18:30:53,231 run_test.py[line:16] INFO: start run test case！
2019-06-01 18:30:53,237 start_driver.py[line:27] INFO: start app...
2019-06-01 18:31:57,891 common_func.py[line:53] INFO: get login screenshot
2019-06-01 18:32:11,449 loginPage.py[line:83] INFO: login success!
2019-06-01 18:35:01,748 run_test.py[line:16] INFO: start run test case！
2019-06-01 18:35:01,754 start_driver.py[line:27] INFO: start app...
2019-06-01 18:36:05,477 common_func.py[line:53] INFO: get login screenshot
2019-06-01 18:36:20,089 loginPage.py[line:83] INFO: login success!
2019-06-01 18:36:26,394 start_driver.py[line:27] INFO: start app...
2019-06-01 18:37:30,108 common_func.py[line:53] INFO: get login screenshot
2019-06-01 18:37:45,855 loginPage.py[line:79] INFO: login fail!
2019-06-01 18:37:45,855 common_func.py[line:53] INFO: get login fail screenshot
2019-06-01 18:37:52,442 start_driver.py[line:27] INFO: start app...
2019-06-01 18:38:56,457 common_func.py[line:53] INFO: get login screenshot
2019-06-01 18:39:11,793 loginPage.py[line:79] INFO: login fail!
2019-06-01 18:39:11,793 common_func.py[line:53] INFO: get login fail screenshot
2019-06-01 18:39:18,332 start_driver.py[line:27] INFO: start app...
2019-06-01 18:40:22,711 common_func.py[line:53] INFO: get login screenshot
2019-06-01 18:40:38,560 loginPage.py[line:79] INFO: login fail!
2019-06-01 18:40:38,560 common_func.py[line:53] INFO: get login fail screenshot
2019-06-02 11:09:37,386 run_test.py[line:16] INFO: start run test case！
2019-06-02 11:09:37,390 start_driver.py[line:27] INFO: start app...
2019-06-02 11:10:49,876 common_func.py[line:53] INFO: get login screenshot
2019-06-02 11:11:03,541 loginPage.py[line:83] INFO: login success!
2019-06-02 11:11:09,803 start_driver.py[line:27] INFO: start app...
2019-06-02 11:12:12,069 common_func.py[line:53] INFO: get login screenshot
2019-06-02 11:12:27,665 loginPage.py[line:79] INFO: login fail!
2019-06-02 11:12:27,665 common_func.py[line:53] INFO: get login fail screenshot
2019-06-02 11:12:34,146 start_driver.py[line:27] INFO: start app...
2019-06-02 11:13:36,661 common_func.py[line:53] INFO: get login screenshot
2019-06-02 11:13:52,419 loginPage.py[line:79] INFO: login fail!
2019-06-02 11:13:52,419 common_func.py[line:53] INFO: get login fail screenshot
2019-06-02 11:13:58,861 start_driver.py[line:27] INFO: start app...
2019-06-02 11:15:01,429 common_func.py[line:53] INFO: get login screenshot
2019-06-02 11:37:50,173 run_test.py[line:16] INFO: start run test case！
2019-06-02 11:37:50,177 start_driver.py[line:27] INFO: start app...
2019-06-02 11:38:53,040 common_func.py[line:53] INFO: get login screenshot
2019-06-02 11:39:08,782 loginPage.py[line:79] INFO: login fail!
2019-06-02 11:39:08,782 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 15:40:15,149 start_driver.py[line:28] INFO: start app...
2019-06-03 15:40:20,317 start_driver.py[line:34] ERROR: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000243C33BEEF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2019-06-03 15:40:50,558 start_driver.py[line:28] INFO: start app...
2019-06-03 15:40:55,586 start_driver.py[line:34] ERROR: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BCCFA4EE80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2019-06-03 15:47:59,611 start_driver.py[line:29] INFO: start app...
2019-06-03 15:48:04,639 start_driver.py[line:35] ERROR: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A2211512E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2019-06-03 15:49:15,954 start_driver.py[line:30] INFO: start app...
2019-06-03 15:49:20,974 start_driver.py[line:36] ERROR: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015F9E3BDEB8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2019-06-03 15:56:44,454 run_test.py[line:16] INFO: start run test case！
2019-06-03 15:57:55,038 run_test.py[line:16] INFO: start run test case！
2019-06-03 15:58:15,713 run_test.py[line:16] INFO: start run test case！
2019-06-03 15:58:15,839 start_driver.py[line:30] INFO: start app...
2019-06-03 15:59:35,333 common_func.py[line:53] INFO: get login screenshot
2019-06-03 15:59:51,164 loginPage.py[line:79] INFO: login fail!
2019-06-03 15:59:51,165 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 16:03:42,945 run_test.py[line:16] INFO: start run test case！
2019-06-03 16:03:43,081 start_driver.py[line:30] INFO: start app...
2019-06-03 16:36:52,938 run_test.py[line:16] INFO: start run test case！
2019-06-03 16:36:53,075 start_driver.py[line:30] INFO: start app...
2019-06-03 16:38:07,625 common_func.py[line:53] INFO: get login screenshot
2019-06-03 16:38:24,390 loginPage.py[line:79] INFO: login fail!
2019-06-03 16:38:24,390 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 16:40:37,385 run_test.py[line:16] INFO: start run test case！
2019-06-03 16:40:37,534 start_driver.py[line:30] INFO: start app...
2019-06-03 16:41:50,791 common_func.py[line:53] INFO: get login screenshot
2019-06-03 16:42:06,788 loginPage.py[line:79] INFO: login fail!
2019-06-03 16:42:06,789 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 16:42:14,421 start_driver.py[line:30] INFO: start app...
2019-06-03 16:43:11,380 start_driver.py[line:30] INFO: start app...
2019-06-03 16:44:07,069 start_driver.py[line:30] INFO: start app...
2019-06-03 21:04:51,020 run_test.py[line:16] INFO: start run test case！
2019-06-03 21:04:51,038 start_driver.py[line:27] INFO: start app...
2019-06-03 21:06:05,003 common_func.py[line:53] INFO: get login screenshot
2019-06-03 21:06:19,312 loginPage.py[line:83] INFO: login success!
2019-06-03 21:06:25,463 start_driver.py[line:27] INFO: start app...
2019-06-03 21:07:21,619 start_driver.py[line:27] INFO: start app...
2019-06-03 21:08:17,881 start_driver.py[line:27] INFO: start app...
2019-06-03 21:12:43,551 run_test.py[line:16] INFO: start run test case！
2019-06-03 21:12:43,556 start_driver.py[line:27] INFO: start app...
2019-06-03 21:13:45,697 common_func.py[line:53] INFO: get login screenshot
2019-06-03 21:13:59,923 loginPage.py[line:83] INFO: login success!
2019-06-03 21:14:06,057 start_driver.py[line:27] INFO: start app...
2019-06-03 21:15:02,087 start_driver.py[line:27] INFO: start app...
2019-06-03 21:15:58,445 start_driver.py[line:27] INFO: start app...
2019-06-03 21:17:15,150 run_test.py[line:16] INFO: start run test case！
2019-06-03 21:17:15,155 start_driver.py[line:27] INFO: start app...
2019-06-03 21:18:07,129 start_driver.py[line:33] ERROR: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

2019-06-03 21:18:07,131 common_func.py[line:20] ERROR: Failed to get screen size
2019-06-03 21:18:07,131 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-06-03 21:18:12,150 start_driver.py[line:27] INFO: start app...
2019-06-03 21:22:27,245 run_test.py[line:16] INFO: start run test case！
2019-06-03 21:22:27,250 start_driver.py[line:27] INFO: start app...
2019-06-03 21:23:38,292 common_func.py[line:53] INFO: get login screenshot
2019-06-03 21:23:51,871 loginPage.py[line:83] INFO: login success!
2019-06-03 21:23:58,077 start_driver.py[line:27] INFO: start app...
2019-06-03 21:25:06,557 common_func.py[line:53] INFO: get login screenshot
2019-06-03 21:25:26,954 loginPage.py[line:79] INFO: login fail!
2019-06-03 21:25:26,955 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 21:25:33,446 start_driver.py[line:27] INFO: start app...
2019-06-03 21:26:42,623 common_func.py[line:53] INFO: get login screenshot
2019-06-03 21:27:03,183 loginPage.py[line:79] INFO: login fail!
2019-06-03 21:27:03,183 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 21:27:10,070 start_driver.py[line:27] INFO: start app...
2019-06-03 21:28:19,198 common_func.py[line:53] INFO: get login screenshot
2019-06-03 21:28:39,630 loginPage.py[line:79] INFO: login fail!
2019-06-03 21:28:39,630 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 21:41:47,743 run_test.py[line:16] INFO: start run test case！
2019-06-03 21:41:47,748 start_driver.py[line:27] INFO: start app...
2019-06-03 21:41:52,763 start_driver.py[line:33] ERROR: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003577E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2019-06-03 21:41:52,765 common_func.py[line:20] ERROR: Failed to get screen size
2019-06-03 21:41:52,765 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-06-03 21:41:57,776 start_driver.py[line:27] INFO: start app...
2019-06-03 21:42:02,786 start_driver.py[line:33] ERROR: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003597AC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2019-06-03 21:42:02,787 common_func.py[line:20] ERROR: Failed to get screen size
2019-06-03 21:42:02,787 common_func.py[line:43] ERROR: 引导页滑动失败!
2019-06-03 22:21:17,569 run_test.py[line:16] INFO: start run test case！
2019-06-03 22:21:17,575 start_driver.py[line:27] INFO: start app...
2019-06-03 22:22:36,530 common_func.py[line:53] INFO: get login screenshot
2019-06-03 22:22:56,922 loginPage.py[line:79] INFO: login fail!
2019-06-03 22:22:56,922 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 22:23:03,538 start_driver.py[line:27] INFO: start app...
2019-06-03 22:24:14,382 common_func.py[line:53] INFO: get login screenshot
2019-06-03 22:24:34,783 loginPage.py[line:79] INFO: login fail!
2019-06-03 22:24:34,783 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 22:24:41,252 start_driver.py[line:27] INFO: start app...
2019-06-03 22:25:51,332 common_func.py[line:53] INFO: get login screenshot
2019-06-03 22:26:11,712 loginPage.py[line:79] INFO: login fail!
2019-06-03 22:26:11,712 common_func.py[line:53] INFO: get login fail screenshot
2019-06-03 22:26:18,345 start_driver.py[line:27] INFO: start app...
2019-06-03 22:27:27,574 common_func.py[line:53] INFO: get login screenshot
2019-06-03 22:27:48,384 loginPage.py[line:79] INFO: login fail!
2019-06-03 22:27:48,384 common_func.py[line:53] INFO: get login fail screenshot
