2019-05-28 16:45:38,785 start_driver.py[line:26] INFO: start app...
2019-05-28 16:56:25,598 start_driver.py[line:26] INFO: start app...
2019-05-28 17:57:04,733 start_driver.py[line:26] INFO: start app...
2019-05-28 17:57:42,403 common_func.py[line:53] ERROR: No element found
2019-05-29 11:13:20,719 start_driver.py[line:26] INFO: start app...
2019-05-29 11:14:06,841 common_func.py[line:53] ERROR: No element found
2019-05-29 11:15:03,718 start_driver.py[line:26] INFO: start app...
2019-05-29 11:15:51,180 common_func.py[line:53] ERROR: No element found
2019-05-29 11:17:22,106 start_driver.py[line:26] INFO: start app...
2019-05-29 11:19:35,958 start_driver.py[line:26] INFO: start app...
2019-05-29 11:26:32,478 start_driver.py[line:26] INFO: start app...
2019-05-29 12:40:51,976 start_driver.py[line:26] INFO: start app...
2019-05-29 13:43:15,598 start_driver.py[line:26] INFO: start app...
2019-05-29 13:45:11,652 start_driver.py[line:26] INFO: start app...
2019-05-29 13:47:39,988 start_driver.py[line:26] INFO: start app...
2019-05-29 13:49:13,230 start_driver.py[line:26] INFO: start app...
2019-05-29 14:12:31,184 start_driver.py[line:26] INFO: start app...
2019-05-29 14:49:36,405 start_driver.py[line:26] INFO: start app...
2019-05-29 14:51:00,808 common_func.py[line:47] INFO: get login screenshot
2019-05-29 14:51:04,123 loginPage.py[line:44] INFO: login success!
2019-05-29 14:51:29,540 loginPage.py[line:58] INFO: logout success!
2019-05-29 14:51:29,540 common_func.py[line:47] INFO: get logout screenshot
2019-05-29 15:55:51,200 start_driver.py[line:26] INFO: start app...
2019-05-29 15:57:28,422 common_func.py[line:47] INFO: get login screenshot
2019-05-29 15:57:31,452 loginPage.py[line:56] INFO: login success!
2019-05-29 15:57:58,721 loginPage.py[line:70] INFO: logout success!
2019-05-29 15:57:58,721 common_func.py[line:47] INFO: get logout screenshot
2019-05-29 17:07:15,843 read_csv.py[line:19] ERROR: [Errno 2] No such file or directory: 'E:\\PythonAppium\\AppiumProject\\data\\account1.csv'
2019-05-29 17:07:53,769 read_csv.py[line:19] ERROR: list index out of range
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:17:58,133 read_csv.py[line:19] INFO: There is no such data!
2019-05-29 17:18:12,419 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:12,420 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:12,420 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:21,825 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:18:21,825 read_csv.py[line:20] INFO: There is no such data!
2019-05-29 17:55:11,715 getConfig.py[line:19] ERROR: No option 'host1' in section: 'email'
2019-05-29 17:55:33,510 getConfig.py[line:19] ERROR: No section: 'email1'
